/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/config-set/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["apply_config_set"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/check-db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["check_db_connection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/check-kv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["check_kv_connection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/config-reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["config_reload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/config-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["config_test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/extensions/test-post-startup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test_post_startup_commands"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/extensions/test-pre-startup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test_pre_startup_commands"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/external-tools/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["diagnose_external_tools"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/external-tools/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["probe_external_tool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finish_config_set"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/license/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_config_set_license_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/license/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_config_set_license_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/media-backend/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["probe_media_backend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_config_notes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/startup-commands/test-post-startup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test_post_startup_commands_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/startup-commands/test-pre-startup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test_pre_startup_commands_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_config_set_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config-set/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_config_template"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Branding configuration for UI customization */
        BrandingConfig: {
            /** @description Custom footer text/HTML */
            footer_text?: string | null;
            /** @description Custom site/app name */
            logo_name?: string | null;
            /** @description Custom logo image URL */
            logo_url?: string | null;
        };
        ConfigError: {
            column: number;
            key?: string | null;
            line: number;
            message: string;
        };
        ConfigNoteEntry: {
            desc_en: string;
            desc_zh: string;
            example: string;
        };
        ConfigNotesResponse: {
            notes: {
                [key: string]: components["schemas"]["ConfigNoteEntry"];
            };
        };
        ConfigSetApplyRequest: {
            admin_password: string;
            config_path: string;
            toml_content: string;
        };
        ConfigSetApplyResponse: {
            admin_action: string;
            admin_username: string;
            password_hint?: string | null;
        };
        ConfigSetLicenseStatusResponse: {
            aux_id: string;
            branding: components["schemas"]["LicenseItemStatus"];
            branding_config: components["schemas"]["BrandingConfig"];
            /** Format: int32 */
            current_users: number;
            device_code: string;
            hw_id: string;
            /** Format: int32 */
            max_users: number;
            registration: components["schemas"]["LicenseItemStatus"];
            storage_encryption: components["schemas"]["LicenseItemStatus"];
        };
        ConfigSetLicenseUpdateRequest: {
            branding?: null | components["schemas"]["BrandingConfig"];
            branding_license?: null | components["schemas"]["LicenseItem"];
            registration?: null | components["schemas"]["LicenseItem"];
            storage_encryption?: null | components["schemas"]["LicenseItem"];
        };
        ConfigSetStatusResponse: {
            is_config_set_mode: boolean;
            is_permitted: boolean;
            message: string;
        };
        ConfigSetTestReq: {
            toml_content: string;
        };
        ConfigTemplateResponse: {
            config_exists: boolean;
            current_config_content: string;
            current_config_path: string;
        };
        DbCheckRequest: {
            connection_string: string;
            db_type: string;
        };
        ExternalToolDiagnoseReq: {
            configured_values: {
                [key: string]: string;
            };
        };
        ExternalToolDiagnoseResponse: {
            is_mobile_platform: boolean;
            runtime_os: string;
            supported: boolean;
            tools: components["schemas"]["ExternalToolDiagnosticItem"][];
        };
        ExternalToolDiagnosticItem: {
            available: boolean;
            candidates: string[];
            config_key: string;
            current_value?: string | null;
            current_value_works: boolean;
            display_name: string;
            group: string;
            message: string;
            recommendation: string;
            resolved_path?: string | null;
            status_code: string;
            suggested_value?: string | null;
            suggestion_source: string;
            supported: boolean;
            tool_id: string;
            version_line?: string | null;
            warnings: string[];
        };
        ExternalToolProbeReq: {
            tool_id: string;
            value: string;
        };
        ExternalToolProbeResponse: {
            available: boolean;
            current_value: string;
            display_name: string;
            message: string;
            resolved_path?: string | null;
            tool_id: string;
            version_line?: string | null;
        };
        KvCheckRequest: {
            connection_string: string;
            kv_type: string;
        };
        /** @description Individual license item with key and toggle */
        LicenseItem: {
            /** @description Whether this license-controlled feature is enabled */
            enabled: boolean;
            /** @description License key string (Base64) */
            key?: string | null;
        };
        /** @description Individual license validation result */
        LicenseItemStatus: {
            enabled: boolean;
            /** Format: date-time */
            expires_at?: string | null;
            features: string[];
            is_valid: boolean;
            msg: string;
        };
        MediaBackendProbeReq: {
            backend: string;
            device?: string | null;
            ffmpeg_path: string;
        };
        MediaBackendProbeResponse: {
            backend: string;
            backend_available: boolean;
            backend_supported: boolean;
            encoder_name?: string | null;
            ffmpeg_available: boolean;
            ffmpeg_version_line?: string | null;
            message: string;
            warnings: string[];
        };
        Resp: {
            biz_code?: string | null;
            cip?: string;
            /** Format: int32 */
            code: number;
            data: Record<string, never>;
            msg?: string;
            req_id?: string;
            success: boolean;
        };
        StartupCommandResult: {
            command: string;
            error?: string | null;
            /** Format: int32 */
            exit_code?: number | null;
            index: number;
            status: components["schemas"]["StartupCommandStatus"];
            stderr: string;
            stderr_truncated: boolean;
            stdout: string;
            stdout_truncated: boolean;
        };
        /** @enum {string} */
        StartupCommandStatus: "exited" | "running" | "spawn_failed";
        StartupExecutionRequest: {
            toml_content?: string | null;
        };
        StartupExecutionResult: {
            commands: components["schemas"]["StartupCommandResult"][];
            phase: string;
            total_duration_ms: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apply_config_set: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigSetApplyRequest"];
            };
        };
        responses: {
            /** @description Config-set completed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Invalid request or configuration */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Initialization failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    check_db_connection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DbCheckRequest"];
            };
        };
        responses: {
            /** @description Connection successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Connection failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    check_kv_connection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KvCheckRequest"];
            };
        };
        responses: {
            /** @description Connection successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Connection failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    config_reload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration reloaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Configuration reload failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    config_test: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigSetTestReq"];
            };
        };
        responses: {
            /** @description Configuration test passed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Configuration test failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    test_post_startup_commands: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartupExecutionRequest"];
            };
        };
        responses: {
            /** @description Test post-startup commands against draft config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    test_pre_startup_commands: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartupExecutionRequest"];
            };
        };
        responses: {
            /** @description Test pre-startup commands against draft config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    diagnose_external_tools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalToolDiagnoseReq"];
            };
        };
        responses: {
            /** @description Diagnose external desktop tools */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    probe_external_tool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalToolProbeReq"];
            };
        };
        responses: {
            /** @description Probe a configured external tool path */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    finish_config_set: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Config-set finishing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    get_config_set_license_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get license status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    update_config_set_license_key: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigSetLicenseUpdateRequest"];
            };
        };
        responses: {
            /** @description Update license and branding */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    probe_media_backend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaBackendProbeReq"];
            };
        };
        responses: {
            /** @description Probe FFmpeg and video hardware backend */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    get_config_notes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get config notes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    test_post_startup_commands_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartupExecutionRequest"];
            };
        };
        responses: {
            /** @description Test post-startup commands against draft config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    test_pre_startup_commands_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartupExecutionRequest"];
            };
        };
        responses: {
            /** @description Test pre-startup commands against draft config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    get_config_set_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Config-set status retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
    get_config_template: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration templates retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resp"];
                };
            };
        };
    };
}
